<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="contact" autocomplete="off">
    <div class="card-header bg-light">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="#dictionary" role="tab" data-toggle="tab">
                    <i class="bi bi-journal-text me-1"></i> <?= $this->translate('Dictionary'); ?>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="#configuration" role="tab" data-toggle="tab">
                    <i class="bi bi-sliders me-1"></i> <?= $this->translate('Configuration'); ?>
                </a>
            </li>
        </ul>
    </div>
    
    <div class="card-body">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="dictionary" role="tabpanel">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content border-start border-end border-bottom p-3">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade <?php echo $index == 0 ? 'show active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $item); ?>

                        <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                        <div class="mb-3">
                            <div class="input-group">
                                <?= Element::textarea(sprintf('translation[%s][value]', $language->getId()), $entity->getValue(), [
                                    'rows' => 5, 
                                    'class' => 'form-control', 
                                    'placeholder' => $this->translate('Name'), 
                                    'data-wysiwyg' => $entity->getWysiwyg() ? 'true' : null
                                ]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="tab-pane fade" id="configuration" role="tabpanel">
                <?= Element::hidden('item[id]', $entity->getId()); ?>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label fw-bold"><?= $this->translate('WYSIWYG'); ?></label>
                    <div class="col-lg-10 d-flex align-items-center">
                        <div class="form-check form-switch">
                            <?= Element::checkbox('item[wysiwyg]', $entity->getWysiwyg(), ['class' => 'form-check-input', 'id' => 'wysiwyg_check']); ?>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-lg-2 col-form-label fw-bold"><?= $this->translate('Alias'); ?></label>
                    <div class="col-lg-10">
                        <?= Element::text('item[alias]', $entity->getAlias(), ['class' => 'form-control', 'placeholder' => $this->translate('Alias')]); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-footer bg-white border-top">
        <?php $this->loadPartial('actions', [
            'new' => !$entity->getId(),
            'add' => 'Dictionary:Admin:Dictionary@addAction',
            'edit' => 'Dictionary:Admin:Dictionary@editAction',
            'save' => 'Dictionary:Admin:Dictionary@saveAction',
            'cancel' => 'Dictionary:Admin:Dictionary@indexAction'
        ]); ?>
    </div>
</form>