<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="contact" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#dictionary" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Dictionary'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>
    
    <div class="tab-content">
        <div class="tab-pane fade in active" id="dictionary" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $item); ?>

                    <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <div class="input-group">
                            <?php echo Element::textarea(sprintf('translation[%s][value]', $language->getId()), $entity->getValue(), array('rows' => 5, 'class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="configuration" role="tabpanel">
            <?php echo Element::hidden('item[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Alias'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::text('item[alias]', $entity->getAlias(), array('class' => 'form-control', 'placeholder' => $this->translate('Alias'))); ?>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Dictionary:Admin:Dictionary@addAction',
        'edit' => 'Dictionary:Admin:Dictionary@editAction',
        'save' => 'Dictionary:Admin:Dictionary@saveAction',
        'cancel' => 'Dictionary:Admin:Dictionary@indexAction'
    )); ?>

</form>
