<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="btn-group">
        <?php $this->loadPartial('menu', array(
            'items' => array(
                'Dictionary:Admin:Dictionary@addAction' => 'Add new item',
            ),
            'actions' => array(
                'data' => $items,
                'delete' => 'Dictionary:Admin:Dictionary@deleteAction',
            )
        )); ?>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4 class="card-title"><?php $this->show('Dictionary'); ?> <small>(<?= count($items); ?>)</small></h4>
    </div>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($items, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'value'
                    ),

                    array(
                        'column' => 'alias'
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Dictionary:Admin:Dictionary@editAction', $row['id']),
                            $this->translate('Edit this item')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Dictionary:Admin:Dictionary@deleteAction', $row['id']),
                            $this->translate('Remove this item')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($items)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No items'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>