<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Dictionary:Admin:Dictionary@addAction'); ?>"><i class="glyphicon glyphicon-phone-alt"></i> <?php $this->show('Add new item'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 <?php if (!empty($items)): ?>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Dictionary:Admin:Dictionary@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Dictionary')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center">
                        <?php if (!empty($items)): ?>
						<input type="checkbox" />
                        <?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Value'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>

            <?php if (!empty($items)): ?>
			<tbody>
                <?php foreach ($items as $item): ?>
				<tr>
					<td class="text-center">
                        <input type="checkbox" name="toDelete[<?php echo $item->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $item->getId(); ?></td>
					<td class="text-center"><?php echo $item->getAlias(); ?></td>
					<td class="text-center"><?php echo $item->getValue(); ?></td>
					<td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this item'); ?>" data-button="edit" href="<?php echo $this->url('Dictionary:Admin:Dictionary@editAction', $item->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this item'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Dictionary:Admin:Dictionary@deleteAction', $item->getId()); ?>"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
		</table>

		<?php if (empty($items)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No items'); ?></h2>
		</div>
		<?php endif; ?>

	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
